language: java
sudo: false

matrix:
  include:
    - jdk: openjdk11
#    - jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
  - chmod +x gradlew
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker
#  - postgresql

#before_script:
#  - psql -c 'create database test;' -U postgres

script:
  - ./gradlew clean test

branches:
  only:
    - spring-boot

notifications:
  email:
    on_success: never
    on_failure: always
