version: '3.5'
services:
  hola:
    build:
      context: ./
      dockerfile: Dockerfile-build
    image: docker-visits
    ports:
      - "8080:8080"
    networks:
      - network1

networks:
  network1:
