version: '3.5'
services:
  redis-server:
    image: redis
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:8081"
    volumes:
      - /app/node_modules
#      - .:/app
