server:
  port: 8080

spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://192.168.99.100:5432/test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
