# https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

GET http://localhost:8080;

###

# https://www.jetbrains.com/help/idea/exploring-http-syntax.html
GET http://192.168.99.100:8080

###
